excluded: 
  - Pods
  - CafeUITests

disabled_rules:
  - trailing_whitespace
  - large_tuple
  - vertical_whitespace
  - type_body_length
  - function_body_length
  - line_length
  - file_length
  - type_name
  - function_parameter_count

line_length: 200
cyclomatic_complexity:
  ignores_case_statements: true

custom_rules: 
  empty_first_line:
    name: "Empty First Line"
    regex: "(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\\{\n *\\S+)"
    message: "There should be an empty line after a declaration"
    severity: warning
  empty_line_after_mark:
    name: "Empty Line After Mark"
    regex: "(^ *\\/\\/MARK\\:[ a-zA-Z0-9=?.\\(\\)\\{\\}:,><!]*\\n *(?!(?:\\}|return))\\S+)"
    message: "There should be an empty line after mark"
    severity: warning
